
DECLARE
v_max_id NUMBER;
  v_count  NUMBER;
BEGIN
SELECT NVL(MAX(idOpcion), 0) + 1 INTO v_max_id FROM Opciones;
SELECT COUNT(*) INTO v_count FROM user_sequences WHERE sequence_name = 'OPCIONES_SEQ';
IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SEQUENCE OPCIONES_SEQ START WITH ' || 500 || ' INCREMENT BY 1 NOCACHE';
END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_OPCIONES_SEQ
BEFORE INSERT ON Opciones
FOR EACH ROW
BEGIN
  IF :NEW.idOpcion IS NULL THEN
SELECT OPCIONES_SEQ.NEXTVAL INTO :NEW.idOpcion FROM dual;
END IF;
END;
/
